language: java
jdk:
  - openjdk8

services:
  - docker

before_install:
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t thiago1432/api-funcionarios-2.0.3 .
- docker run -d -p 127.0.0.1:8090  thiago1432/api-funcionarios-2.0.3
- docker ps -a

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
