# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-funcionarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-funcionarios
  template:
    metadata:
      labels:
        app: api-funcionarios
    spec:
      containers:
        - name: app
          image: thiago1432/api-funcionarios-2.0.1
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: api-funcionarios
spec:
  selector:
    app: api-funcionarios
  ports:
    - port: 80
      targetPort: 8080
  externalIPs:
    - 1.2.4.120
  type: LoadBalancer