# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-funcionarios
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-funcionarios
  template:
    metadata:
      labels:
        app: api-funcionarios
    spec:
      containers:
        - name: api-funcionarios
          image: thiago1432/api-funcionarios-2.0.2
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: api-funcionarios
spec:
  selector:
    app: api-funcionarios
  ports:
    - port: 8085
      targetPort: 80
      nodePort: 30001
  type: LoadBalancer