apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-funcionarios-v2
spec: 
  selector:
    matchLabels:
      app: api-funcionarios-v2
  template:
    metadata:
      #creationTimestamp: null
      labels:
        app: api-funcionarios-v2
    spec:
      containers:
        - name: api-funcionarios
          image: thiago1432/api-funcionarios-2.0.2
          ports: 
          - containerPort: 80
#        resources: {}
#status: {}
